[project]
name = "tcp-framework"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "gitpython>=3.1.44",
    "pandas>=2.2.3",
    "sentence-transformers>=4.0.1",
]

[dependency-groups]
dev = [
    "mypy>=1.15.0",
    "pandas-stubs>=2.2.3.250308",
    "ruff>=0.11.2",
]
